import io
import re
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    Paragraph, Spacer, Table, TableStyle,
    HRFlowable, BaseDocTemplate, PageTemplate, Frame
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.pdfgen import canvas

W, H = A4

# ── 色盤 ──────────────────────────────────────────────────────────────
NAVY     = colors.HexColor("#1E3A5F")
BLUE     = colors.HexColor("#378ADD")
BLUE_LT  = colors.HexColor("#E6F1FB")
BLUE_MD  = colors.HexColor("#B5D4F4")
GREEN    = colors.HexColor("#1D9E75")
GRAY_LT  = colors.HexColor("#F5F5F5")
GRAY_BD  = colors.HexColor("#CCCCCC")
GRAY_TX  = colors.HexColor("#888780")
DIFF_BG  = colors.HexColor("#FAEEDA")
WHITE    = colors.white
BLACK    = colors.HexColor("#1A1A1A")


# ── Header / Footer ───────────────────────────────────────────────────
class ReportCanvas(canvas.Canvas):
    """自訂 Canvas，在每頁加上 header 與 footer。"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = max(len(self._saved_page_states), 1)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_chrome(total)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def _draw_chrome(self, total: int):
        from datetime import date
        today = date.today().strftime("%Y-%m-%d")

        # Header 深藍底
        self.setFillColor(NAVY)
        self.rect(0, H - 22 * mm, W, 22 * mm, fill=1, stroke=0)

        # 品牌名稱
        self.setFillColor(WHITE)
        self.setFont("Helvetica-Bold", 13)
        self.drawString(15 * mm, H - 13 * mm, "Advantech")

        # 副標題
        self.setFont("Helvetica", 9)
        self.setFillColor(BLUE_MD)
        self.drawString(15 * mm, H - 18.5 * mm,
                        "Industrial Switch Selection Report")

        # 右上：日期 + 頁碼
        self.setFillColor(WHITE)
        self.setFont("Helvetica", 8)
        self.drawRightString(W - 15 * mm, H - 12 * mm,
                             f"Generated: {today}")
        self.drawRightString(W - 15 * mm, H - 17.5 * mm,
                             f"Page {self._pageNumber} / {total}")

        # Footer 分隔線
        self.setStrokeColor(GRAY_BD)
        self.setLineWidth(0.5)
        self.line(15 * mm, 12 * mm, W - 15 * mm, 12 * mm)

        # Footer 文字
        self.setFillColor(GRAY_TX)
        self.setFont("Helvetica", 7.5)
        self.drawString(15 * mm, 8 * mm,
                        "Generated by Advantech Industrial Switch Selection Tool")
        self.drawRightString(W - 15 * mm, 8 * mm, "www.advantech.com")


# ── 工具函式 ──────────────────────────────────────────────────────────
def PS(name: str, size: int = 9, bold: bool = False,
       color=BLACK, align=TA_LEFT, leading: int = 13) -> ParagraphStyle:
    return ParagraphStyle(
        name,
        fontName="Helvetica-Bold" if bold else "Helvetica",
        fontSize=size, textColor=color,
        alignment=align, leading=leading,
    )


def V(text: str, bold: bool = False,
      align=TA_CENTER, color=BLACK) -> Paragraph:
    return Paragraph(
        str(text) if text else "—",
        PS(f"v{hash(text)}", 8, bold, color, align),
    )


def L(text: str) -> Paragraph:
    return Paragraph(text, PS(f"l{hash(text)}", 8, False, GRAY_TX))


def sec_header(label: str) -> list:
    return [
        Paragraph(f"  {label}",
                  PS(f"sec{hash(label)}", 8, True, GRAY_TX)),
        "", "", "", ""
    ]


TICK  = V("✓", True,  TA_CENTER, GREEN)
CROSS = V("✗", False, TA_CENTER, GRAY_TX)
DASH  = V("—", False, TA_CENTER, GRAY_TX)


def yn(val) -> Paragraph:
    """'full' → TICK, 其他 → CROSS"""
    if str(val).lower() == "full":
        return TICK
    return CROSS


def safe_int(v) -> int:
    try:
        return int(str(v).strip())
    except Exception:
        return 0


def port_val(hw: dict, *keys) -> Paragraph:
    """取多個欄位的加總，>0 顯示數字，否則顯示 —"""
    total = sum(safe_int(hw.get(k)) for k in keys)
    return V(str(total)) if total > 0 else DASH


# ── 主要產生函式 ──────────────────────────────────────────────────────
def generate_selection_report(products: list[dict], criteria: dict, ai_summary: str = "") -> bytes:
    buffer = io.BytesIO()

    doc = BaseDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=28 * mm, bottomMargin=20 * mm,
    )
    frame = Frame(15 * mm, 20 * mm, W - 30 * mm, H - 48 * mm, id="main")
    doc.addPageTemplates([PageTemplate(id="main", frames=frame)])

    story = []
    n = len(products)  # 產品數量（最多 5）
    if n == 0:
        story.append(Paragraph("No products selected", PS("h1", 16, True, NAVY, leading=20)))
        doc.build(story, canvasmaker=ReportCanvas)
        buffer.seek(0)
        return buffer.read()

    # 動態欄寬：左側 label 欄固定 40mm，其餘均分
    available = W - 30 * mm  # 總可用寬度
    label_w   = 40 * mm
    prod_w    = (available - label_w) / max(n, 1)
    col_widths = [label_w] + [prod_w] * n

    # ── Section 1: 選型條件摘要 ───────────────────────────────────────
    story.append(Paragraph("Selection Criteria Summary",
                            PS("h1", 16, True, NAVY, leading=20)))
    story.append(HRFlowable(width="100%", thickness=1.5,
                             color=BLUE, spaceAfter=6))

    items_list = criteria.get("items", [])
    item_set   = set(items_list)

    # Management Type
    type_map = {
        "all": "All Types",
        "managed": "Managed (L2 + L3)",
        "l2_managed": "L2 Managed",
        "l3_managed": "L3 Managed",
        "unmanaged": "Unmanaged",
    }
    raw_type = criteria.get("type", "ALL")
    if isinstance(raw_type, list):
        raw_type = raw_type[0] if raw_type else "ALL"
    req_type = str(raw_type).strip().lower()
    formatted_type = type_map.get(req_type) or str(raw_type).replace("_", " ").title()

    # Min Port Count
    port_display = (f"≥ {criteria.get('portnum')} ports"
                    if criteria.get("portnum", -1) > 0 else "No limit")

    # Max Port Speed
    speed_map = {"Speed_100M": "100M", "Speed_GbE": "1G", "Speed_10G": "10G+"}
    speed_display = next((v for k, v in speed_map.items() if k in item_set), "Any")

    # PoE
    poe_display = "Required" if "Has_PoE" in item_set else "Not Required"

    # Interface Type
    iface_parts = []
    if "Has_RJ-45" in item_set: iface_parts.append("RJ-45")
    if "Has_Fiber"  in item_set: iface_parts.append("Fiber")
    iface_display = ", ".join(iface_parts) if iface_parts else "Any"

    # Certifications
    cert_map = {
        "Cert_UL": "UL", "Cert_LVD": "LVD", "Cert_IEC61850": "IEC 61850",
        "Cert_NEMA": "NEMA", "Cert_EN50155": "EN 50155",
        "Cert_EMark": "E-Mark", "Cert_ITxPT": "ITxPT",
    }
    cert_parts = [label for key, label in cert_map.items() if key in item_set]
    cert_display = ", ".join(cert_parts) if cert_parts else "None"

    crit_rows = [
        [Paragraph("<b>Criteria</b>", PS("ch", 8, color=WHITE)),
         Paragraph("<b>Value</b>",    PS("cv", 8, color=WHITE))],
        ["Management Type",   formatted_type],
        ["Min Port Count",    port_display],
        ["Max Port Speed",    speed_display],
        ["PoE Required",      poe_display],
        ["Interface Type",    iface_display],
        ["Certifications",    cert_display],
    ]
    crit_tbl = Table(crit_rows, colWidths=[55 * mm, 115 * mm])
    crit_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), NAVY),
        ("FONTNAME",      (0, 1), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 8.5),
        ("TEXTCOLOR",     (0, 1), (0, -1), GRAY_TX),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, GRAY_LT]),
        ("GRID",          (0, 0), (-1, -1), 0.4, GRAY_BD),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
    ]))
    story.append(crit_tbl)

    # 其他已選功能項目（排除已在表格中顯示的條件）
    known_keys = set(speed_map) | {"Has_PoE", "Has_RJ-45", "Has_Fiber"} | set(cert_map)
    item_labels = criteria.get("itemLabels", {})
    extra_labels = [label for k, label in item_labels.items() if k not in known_keys]
    if extra_labels:
        story.append(Spacer(1, 4))
        story.append(Paragraph("<b>Selected Features:</b>",
                                PS("sh3", 8, color=GRAY_TX)))
        for label in extra_labels:
            story.append(Paragraph(f"  • {label}",
                                    PS(f"sm{hash(label)}", 8, color=GRAY_TX)))

    story.append(Spacer(1, 10))

    # ── Section 2: 硬體規格比較表 ────────────────────────────────────
    story.append(Paragraph("Hardware Specification Comparison",
                            PS("h1", 16, True, NAVY, leading=20)))
    story.append(HRFlowable(width="100%", thickness=1.5,
                             color=BLUE, spaceAfter=6))
    story.append(Paragraph(
        f"{n} product{'s' if n > 1 else ''} match all selected criteria. "
        "Highlighted cells indicate differences between products.",
        PS("body", 9),
    ))
    story.append(Spacer(1, 6))

    # ── 動態建立比較表 ────────────────────────────────────────────────
    def hw(i: int) -> dict:
        return products[i].get("hardware", {})

    def sw(i: int) -> dict:
        return products[i].get("software", {})

    def sw_val(i: int, category: str, key: str) -> Paragraph:
        val = sw(i).get(category, {}).get(key, "no")
        return yn(val)

    # Header row — 白字在深藍底
    header_row = [Paragraph("", PS("hdr_lbl", 8, color=WHITE))]
    for i in range(n):
        model = products[i].get("model_name") or hw(i).get("Model Name", "—")
        pn    = products[i].get("product_pn", "—")
        header_row.append(Paragraph(
            f"<b>{model}</b><br/><font size='7'>{pn}</font>",
            PS(f"hdr{i}", 9, True, WHITE, TA_CENTER, leading=13)
        ))

    def make_row(label: str, vals: list) -> list:
        return [L(label)] + vals

    def get_text(p) -> str:
        """取出 Paragraph 的純文字（用於比較）"""
        if hasattr(p, "text"):
            return p.text or ""
        return str(p)

    def diff_indices(vals: list) -> bool:
        """判斷這一行是否有差異"""
        texts = [get_text(p) for p in vals]
        return len(set(texts)) > 1

    # 所有資料列
    rows = [header_row]
    sec_row_indices = set()
    # diff_cells: list of (row_idx, col_idx) to highlight
    diff_cells: list = []

    def add_sec(label):
        sec_row_indices.add(len(rows))
        sec_r = [Paragraph(f"  {label}", PS(f"sec{hash(label)}", 8, True, GRAY_TX))]
        for _ in range(n): sec_r.append("")
        rows.append(sec_r)

    def has_any_value(vals):
        """至少一欄有非零/非空值才加入表格（與網頁比較表邏輯一致）"""
        for p in vals:
            txt = get_text(p)
            if txt and txt != "—":
                return True
        return False

    def add_row(label, vals):
        if not has_any_value(vals):
            return
        row_idx = len(rows)
        if diff_indices(vals):
            texts = [get_text(p) for p in vals]
            base = texts[0]
            for col, txt in enumerate(texts):
                if txt != base:
                    # col 0 = label col, product cols start at 1
                    diff_cells.append((row_idx, col + 1))
        rows.append(make_row(label, vals))

    def format_mgmt(val):
        if not val or val == "—": return "—"
        v = str(val).strip().lower()
        if v in ("l2_managed", "l2 managed"): return "L2 Managed"
        if v in ("l3_managed", "l3 managed"): return "L3 Managed"
        if "unmanage" in v: return "Unmanaged"
        if v in ("managed", "manage"): return "Managed (L2 + L3)"
        return str(val).replace("_", " ").title()

    # Basic Information
    add_sec("Basic Information")
    add_row("Management Type",
            [V(format_mgmt(hw(i).get("Function", "—"))) for i in range(n)])
    add_row("Total Ports",
            [V(hw(i).get("Port Numbers", "—"), True) for i in range(n)])
    add_row("Temp Range",
            [V(hw(i).get("Op Temp Range") or hw(i).get("Temp Grade") or "—") for i in range(n)])
    add_row("Power Input",
            [V(hw(i).get("Input Voltage") or "—") for i in range(n)])
    add_row("Mounting Type",
            [V(hw(i).get("Type") or "—") for i in range(n)])

    # Port Specification
    add_sec("Port Specification")
    add_row("RJ-45 10/100M",
            [port_val(hw(i), "RJ-45 10/100M") for i in range(n)])
    add_row("RJ-45 GbE",
            [port_val(hw(i), "RJ-45 Gigabit") for i in range(n)])
    add_row("PoE RJ-45 100M",
            [port_val(hw(i), "PoE RJ-45 100M") for i in range(n)])
    add_row("PoE RJ-45 GbE",
            [port_val(hw(i), "PoE RJ-45 GbE") for i in range(n)])
    add_row("Fiber 100M",
            [port_val(hw(i), "Fiber 100M") for i in range(n)])
    add_row("Fiber GbE (SFP)",
            [port_val(hw(i), "Fiber Gigabit", "Fiber GE Combo") for i in range(n)])
    add_row("Fiber 10G (SFP+)",
            [port_val(hw(i), "Fiber 10G") for i in range(n)])
    add_row("RJ-45 / SFP Combo",
            [port_val(hw(i), "RJ-45 Combo") for i in range(n)])
    add_row("M12 D-code 100M",
            [port_val(hw(i), "Eth 10/100M (D-code)") for i in range(n)])
    add_row("M12 X-code GbE",
            [port_val(hw(i), "Eth Gigabit (X-code)") for i in range(n)])
    add_row("M12 X-code Multi-Giga",
            [port_val(hw(i), "Eth Multi-Giga (X-code)") for i in range(n)])
    add_row("PoE M12 D-code",
            [port_val(hw(i), "PoE (D-code)") for i in range(n)])
    add_row("PoE M12 X-code",
            [port_val(hw(i), "PoE (X-code)") for i in range(n)])
    add_row("PoE Standard",
            [V(hw(i).get("PoE Standard") or "—") for i in range(n)])
    add_row("PoE Budget (W)",
            [V(hw(i).get("Power Budget (W)") or "—") for i in range(n)])
    add_row("LAN Bypass D-code",
            [port_val(hw(i), "LAN Bypass 10/100M (D-code)") for i in range(n)])
    add_row("LAN Bypass X-code",
            [port_val(hw(i), "LAN Bypass Gigabit (X-code)") for i in range(n)])

    # Fiber Specification
    add_sec("Fiber Specification")
    add_row("Fiber Slot Type",
            [V(hw(i).get("Fiber Type") or "—") for i in range(n)])
    add_row("Fixed Connector",
            [V(hw(i).get("Fiber Connector") or "—") for i in range(n)])

    # Certifications
    add_sec("Certifications")
    add_row("Certifications",
            [V(hw(i).get("Certifications") or "—") for i in range(n)])

    # 組成 Table
    spec_tbl = Table(rows, colWidths=col_widths, repeatRows=1)

    style_cmds = [
        ("FONTSIZE",       (0, 0), (-1, -1), 8.5),
        ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",     (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 4),
        ("LEFTPADDING",    (0, 0), (-1, -1), 6),
        ("GRID",           (0, 0), (-1, -1), 0.3, GRAY_BD),
        # Header row — 全部產品欄統一深藍底白字
        ("BACKGROUND",     (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR",      (0, 0), (-1, 0), WHITE),
        # Label col
        ("BACKGROUND",     (0, 1), (0, -1), GRAY_LT),
    ]
    for r in sec_row_indices:
        style_cmds += [
            ("BACKGROUND", (0, r), (-1, r), colors.HexColor("#D6E4F0")),
            ("SPAN",       (0, r), (-1, r)),
        ]
    for (r, c) in diff_cells:
        style_cmds.append(("BACKGROUND", (c, r), (c, r), DIFF_BG))

    spec_tbl.setStyle(TableStyle(style_cmds))
    story.append(spec_tbl)
    story.append(Spacer(1, 4))

    # 圖例
    leg = Table([[
        Paragraph("", PS("lx", 7)),
        Paragraph(
            "  Highlighted cells indicate differences between products",
            PS("ll", 7, color=GRAY_TX),
        ),
    ]], colWidths=[6 * mm, available - 6 * mm])
    leg.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (0, 0), DIFF_BG),
        ("BOX",           (0, 0), (0, 0), 0.4, GRAY_BD),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(leg)
    story.append(Spacer(1, 10))

    # ── Section 3: AI Summary ─────────────────────────────────────────
    story.append(Paragraph("AI Analysis Summary",
                            PS("h1", 16, True, NAVY, leading=20)))
    story.append(HRFlowable(width="100%", thickness=1.5,
                             color=BLUE, spaceAfter=6))

    ai_text = ai_summary.strip() if ai_summary and ai_summary.strip() else "AI analysis not available."

    def _md_to_rl(text: str) -> str:
        """Convert markdown bold/italic/code to ReportLab XML markup."""
        text = re.sub(r'\*\*([^*]+)\*\*', r'<b>\1</b>', text)
        text = re.sub(r'\*([^*]+)\*', r'\1', text)
        text = re.sub(r'`([^`]+)`', r'\1', text)
        return text

    for line in ai_text.splitlines():
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 4))
        elif stripped.startswith("## "):
            story.append(Paragraph(_md_to_rl(stripped[3:]), PS(f"aih{hash(stripped)}", 10, True, NAVY, leading=14)))
            story.append(Spacer(1, 2))
        elif stripped.startswith("- ") or stripped.startswith("* "):
            story.append(Paragraph(f"  • {_md_to_rl(stripped[2:])}", PS(f"aib{hash(stripped)}", 8.5, color=BLACK, leading=13)))
        else:
            story.append(Paragraph(_md_to_rl(stripped), PS(f"aip{hash(stripped)}", 8.5, color=BLACK, leading=13)))

    story.append(Spacer(1, 10))

    # ── Section 4: 參考連結 ───────────────────────────────────────────
    story.append(Paragraph("Product References",
                            PS("h2", 11, True, NAVY, leading=16)))
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=GRAY_BD, spaceAfter=5))

    ref_rows = [[
        Paragraph("<b>Model</b>",    PS("rh",  8, color=WHITE)),
        Paragraph("<b>Part No.</b>", PS("rh2", 8, color=WHITE)),
        Paragraph("<b>Product Page</b>", PS("rh3", 8, color=WHITE)),
    ]]
    for p in products:
        model = p.get("model_name") or p.get("hardware", {}).get("Model Name", "—")
        pn    = p.get("product_pn",  "—")
        url   = (p.get("url")
                 or f"https://www.advantech.com/en/search?q={model}")
        ref_rows.append([
            Paragraph(model, PS("rm", 8, True)),
            Paragraph(pn,    PS("rp", 8, color=GRAY_TX)),
            Paragraph(
                f'<link href="{url}" color="#378ADD">{url}</link>',
                PS("rl", 8),
            ),
        ])

    ref_tbl = Table(ref_rows, colWidths=[38 * mm, 44 * mm, available - 82 * mm])
    ref_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), NAVY),
        ("FONTSIZE",      (0, 0), (-1, -1), 8.5),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, GRAY_LT]),
        ("GRID",          (0, 0), (-1, -1), 0.4, GRAY_BD),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
    ]))
    story.append(ref_tbl)

    # ── Build ─────────────────────────────────────────────────────────
    doc.build(story, canvasmaker=ReportCanvas)
    buffer.seek(0)
    return buffer.read()
