import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    Paragraph, Spacer, Table, TableStyle,
    HRFlowable, BaseDocTemplate, PageTemplate, Frame
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.pdfgen import canvas

W, H = A4

# ── 色盤 ──────────────────────────────────────────────────────────────
NAVY     = colors.HexColor("#1E3A5F")
BLUE     = colors.HexColor("#378ADD")
BLUE_LT  = colors.HexColor("#E6F1FB")
BLUE_MD  = colors.HexColor("#B5D4F4")
GREEN    = colors.HexColor("#1D9E75")
GRAY_LT  = colors.HexColor("#F5F5F5")
GRAY_BD  = colors.HexColor("#CCCCCC")
GRAY_TX  = colors.HexColor("#888780")
DIFF_BG  = colors.HexColor("#FAEEDA")
WHITE    = colors.white
BLACK    = colors.HexColor("#1A1A1A")


# ── Header / Footer ───────────────────────────────────────────────────
class ReportCanvas(canvas.Canvas):
    """自訂 Canvas，在每頁加上 header 與 footer。"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = max(len(self._saved_page_states), 1)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_chrome(total)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def _draw_chrome(self, total: int):
        from datetime import date
        today = date.today().strftime("%Y-%m-%d")

        # Header 深藍底
        self.setFillColor(NAVY)
        self.rect(0, H - 22 * mm, W, 22 * mm, fill=1, stroke=0)

        # 品牌名稱
        self.setFillColor(WHITE)
        self.setFont("Helvetica-Bold", 13)
        self.drawString(15 * mm, H - 13 * mm, "Advantech")

        # 副標題
        self.setFont("Helvetica", 9)
        self.setFillColor(BLUE_MD)
        self.drawString(15 * mm, H - 18.5 * mm,
                        "Industrial Switch Selection Report")

        # 右上：日期 + 頁碼
        self.setFillColor(WHITE)
        self.setFont("Helvetica", 8)
        self.drawRightString(W - 15 * mm, H - 12 * mm,
                             f"Generated: {today}")
        self.drawRightString(W - 15 * mm, H - 17.5 * mm,
                             f"Page {self._pageNumber} / {total}")

        # Footer 分隔線
        self.setStrokeColor(GRAY_BD)
        self.setLineWidth(0.5)
        self.line(15 * mm, 12 * mm, W - 15 * mm, 12 * mm)

        # Footer 文字
        self.setFillColor(GRAY_TX)
        self.setFont("Helvetica", 7.5)
        self.drawString(15 * mm, 8 * mm,
                        "Generated by Advantech Industrial Switch Selection Tool")
        self.drawRightString(W - 15 * mm, 8 * mm, "www.advantech.com")


# ── 工具函式 ──────────────────────────────────────────────────────────
def PS(name: str, size: int = 9, bold: bool = False,
       color=BLACK, align=TA_LEFT, leading: int = 13) -> ParagraphStyle:
    return ParagraphStyle(
        name,
        fontName="Helvetica-Bold" if bold else "Helvetica",
        fontSize=size, textColor=color,
        alignment=align, leading=leading,
    )


def V(text: str, bold: bool = False,
      align=TA_CENTER, color=BLACK) -> Paragraph:
    return Paragraph(
        str(text) if text else "—",
        PS(f"v{hash(text)}", 8, bold, color, align),
    )


def L(text: str) -> Paragraph:
    return Paragraph(text, PS(f"l{hash(text)}", 8, False, GRAY_TX))


def sec_header(label: str) -> list:
    return [
        Paragraph(f"  {label}",
                  PS(f"sec{hash(label)}", 8, True, GRAY_TX)),
        "", "", "", ""
    ]


TICK  = V("✓", True,  TA_CENTER, GREEN)
CROSS = V("✗", False, TA_CENTER, GRAY_TX)
DASH  = V("—", False, TA_CENTER, GRAY_TX)


def yn(val) -> Paragraph:
    """'full' → TICK, 其他 → CROSS"""
    if str(val).lower() == "full":
        return TICK
    return CROSS


def safe_int(v) -> int:
    try:
        return int(str(v).strip())
    except Exception:
        return 0


def port_val(hw: dict, *keys) -> Paragraph:
    """取多個欄位的加總，>0 顯示數字，否則顯示 —"""
    total = sum(safe_int(hw.get(k)) for k in keys)
    return V(str(total)) if total > 0 else DASH


# ── 主要產生函式 ──────────────────────────────────────────────────────
def generate_selection_report(products: list[dict], criteria: dict) -> bytes:
    buffer = io.BytesIO()

    doc = BaseDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=28 * mm, bottomMargin=20 * mm,
    )
    frame = Frame(15 * mm, 20 * mm, W - 30 * mm, H - 48 * mm, id="main")
    doc.addPageTemplates([PageTemplate(id="main", frames=frame)])

    story = []
    n = len(products)  # 產品數量（最多 5）
    if n == 0:
        story.append(Paragraph("No products selected", PS("h1", 16, True, NAVY, leading=20)))
        doc.build(story, canvasmaker=ReportCanvas)
        buffer.seek(0)
        return buffer.read()

    # 動態欄寬：左側 label 欄固定 40mm，其餘均分
    available = W - 30 * mm  # 總可用寬度
    label_w   = 40 * mm
    prod_w    = (available - label_w) / max(n, 1)
    col_widths = [label_w] + [prod_w] * n

    # ── Section 1: 選型條件摘要 ───────────────────────────────────────
    story.append(Paragraph("Selection Criteria Summary",
                            PS("h1", 16, True, NAVY, leading=20)))
    story.append(HRFlowable(width="100%", thickness=1.5,
                             color=BLUE, spaceAfter=6))

    # 管理類型友善顯示
    type_map = {
        "all": "All Types",
        "managed": "Managed (L2 + L3)",
        "l2_managed": "L2 Managed",
        "l3_managed": "L3 Managed",
        "unmanaged": "Unmanaged",
    }
    port_display = (f"≥ {criteria.get('portnum')} ports"
                    if criteria.get("portnum", -1) > 0 else "No limit")
    app_display  = criteria.get("application", "ALL")
    if app_display == "ALL":
        app_display = "All Applications"

    raw_type = criteria.get("type", "ALL")
    if isinstance(raw_type, list):
        raw_type = raw_type[0] if raw_type else "ALL"
    req_type = str(raw_type).strip().lower()
    print(f'[DEBUG] export PDF raw_type={raw_type}, req_type={req_type}', flush=True)

    formatted_type = type_map.get(req_type)
    if not formatted_type:
        formatted_type = str(raw_type).replace("_", " ").title().replace("L2 ", "L2 ").replace("L3 ", "L3 ")

    crit_rows = [
        [Paragraph("<b>Criteria</b>", PS("ch", 8, color=WHITE)),
         Paragraph("<b>Value</b>",    PS("cv", 8, color=WHITE))],
        ["Management Type", formatted_type],
        ["Minimum Port Count", port_display],
        ["Application",        app_display],
    ]
    crit_tbl = Table(crit_rows, colWidths=[55 * mm, 115 * mm])
    crit_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), NAVY),
        ("FONTNAME",      (0, 1), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 8.5),
        ("TEXTCOLOR",     (0, 1), (0, -1), GRAY_TX),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, GRAY_LT]),
        ("GRID",          (0, 0), (-1, -1), 0.4, GRAY_BD),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
    ]))
    story.append(crit_tbl)

    # 已選功能項目：儲存在 itemLabels 中（否則從 items list fallback）
    item_labels = criteria.get("itemLabels", {})
    items_list  = criteria.get("items", [])
    if item_labels:
        story.append(Spacer(1, 4))
        story.append(Paragraph("<b>Selected Features:</b>",
                                PS("sh3", 8, color=GRAY_TX)))
        for k, label in item_labels.items():
            story.append(Paragraph(f"  • {label}",
                                    PS(f"sm{hash(k)}", 8, color=GRAY_TX)))
    elif items_list:
        story.append(Spacer(1, 4))
        story.append(Paragraph("<b>Selected Features:</b>",
                                PS("sh3", 8, color=GRAY_TX)))
        for item in items_list:
            label = item.split("|||")[-1] if "|||" in item else item
            story.append(Paragraph(f"  • {label}",
                                    PS(f"sm{hash(item)}", 8, color=GRAY_TX)))

    story.append(Spacer(1, 10))

    # ── Section 2: 硬體規格比較表 ────────────────────────────────────
    story.append(Paragraph("Hardware Specification Comparison",
                            PS("h1", 16, True, NAVY, leading=20)))
    story.append(HRFlowable(width="100%", thickness=1.5,
                             color=BLUE, spaceAfter=6))
    story.append(Paragraph(
        f"{n} product{'s' if n > 1 else ''} match all selected criteria. "
        "Highlighted cells indicate differences between products.",
        PS("body", 9),
    ))
    story.append(Spacer(1, 6))

    # ── 動態建立比較表 ────────────────────────────────────────────────
    def hw(i: int) -> dict:
        return products[i].get("hardware", {})

    def sw(i: int) -> dict:
        return products[i].get("software", {})

    def sw_val(i: int, category: str, key: str) -> Paragraph:
        val = sw(i).get(category, {}).get(key, "no")
        return yn(val)

    # Header row — 白字在深藍底
    header_row = [Paragraph("", PS("hdr_lbl", 8, color=WHITE))]
    for i in range(n):
        model = products[i].get("model_name") or hw(i).get("Model Name", "—")
        pn    = products[i].get("product_pn", "—")
        header_row.append(Paragraph(
            f"<b>{model}</b><br/><font size='7'>{pn}</font>",
            PS(f"hdr{i}", 9, True, WHITE, TA_CENTER, leading=13)
        ))

    def make_row(label: str, vals: list) -> list:
        return [L(label)] + vals

    def diff_indices(vals: list) -> bool:
        """判斷這一行是否有差異（用於標色）"""
        texts = [p.text if hasattr(p, "text") else str(p) for p in vals]
        return len(set(texts)) > 1

    # 所有資料列
    rows = [header_row]
    sec_row_indices  = set()
    diff_row_indices = set()

    def add_sec(label):
        sec_row_indices.add(len(rows))
        sec_r = [Paragraph(f"  {label}", PS(f"sec{hash(label)}", 8, True, GRAY_TX))]
        for _ in range(n): sec_r.append("")
        rows.append(sec_r)

    def add_row(label, vals):
        if diff_indices(vals):
            diff_row_indices.add(len(rows))
        rows.append(make_row(label, vals))

    def format_mgmt(val):
        if not val or val == "—": return "—"
        v = str(val).strip().lower()
        if v in ("l2_managed", "l2 managed"): return "L2 Managed"
        if v in ("l3_managed", "l3 managed"): return "L3 Managed"
        if "unmanage" in v: return "Unmanaged"
        if v in ("managed", "manage"): return "Managed (L2 + L3)"
        return str(val).replace("_", " ").title()

    # Basic
    add_sec("Basic Information")
    add_row("Management Type",
            [V(format_mgmt(hw(i).get("Function", "—"))) for i in range(n)])
    add_row("Temp Grade",
            [V(hw(i).get("Temp Grade", "—")) for i in range(n)])
    add_row("Operating Temp",
            [V(hw(i).get("Op Temp Range") or hw(i).get("Temp Grade") or "—")
             for i in range(n)])
    add_row("Power Input",
            [V(hw(i).get("Input Voltage") or "—") for i in range(n)])

    # Ports
    add_sec("Port Configuration")
    add_row("Total Ports",
            [V(hw(i).get("Port Numbers", "—"), True) for i in range(n)])
    add_row("RJ-45 GbE",
            [port_val(hw(i), "RJ-45 Gigabit") for i in range(n)])
    add_row("RJ-45 10/100M",
            [port_val(hw(i), "RJ-45 10/100M") for i in range(n)])
    add_row("RJ-45 Combo",
            [port_val(hw(i), "RJ-45 Combo") for i in range(n)])
    add_row("Fiber GbE (SFP)",
            [port_val(hw(i), "Fiber Gigabit", "Fiber GE Combo") for i in range(n)])
    add_row("Fiber 10G (SFP+)",
            [port_val(hw(i), "Fiber 10G") for i in range(n)])
    add_row("PoE RJ-45 GbE",
            [port_val(hw(i), "PoE RJ-45 GbE") for i in range(n)])
    add_row("PoE Standard",
            [V(hw(i).get("PoE Standard") or "—") for i in range(n)])
    add_row("PoE Budget (W)",
            [V(hw(i).get("Power Budget (W)") or "—") for i in range(n)])

    # Redundancy
    add_sec("Redundancy / Ring")
    add_row("X-Ring Elite",
            [sw_val(i, "X-Ring Elite", "Multiple Ring") for i in range(n)])
    add_row("X-Ring Pro",
            [sw_val(i, "X-Ring Pro", "Multiple Ring") for i in range(n)])
    add_row("RSTP (802.1w)",
            [sw_val(i, "Spanning Tree", "IEEE 802.1w RSTP") for i in range(n)])
    add_row("MSTP (802.1s)",
            [sw_val(i, "Spanning Tree", "IEEE 802.1s MSTP") for i in range(n)])
    add_row("ERPS (G.8032)",
            [sw_val(i, "ERPS(G.8032)", "G.8032 ERPS") for i in range(n)])
    add_row("MRP (IEC 62439-2)",
            [sw_val(i, "IEC 62439-2 MRP", "MRM") for i in range(n)])

    # Industrial
    add_sec("Industrial Protocols")
    add_row("PROFINET",
            [sw_val(i, "Industrial Protocol - Modbus TCP", "PROFINET")
             for i in range(n)])
    add_row("EtherNet/IP",
            [sw_val(i, "Industrial Protocol - Modbus TCP", "EtherNet")
             for i in range(n)])
    add_row("Modbus TCP",
            [sw_val(i, "Industrial Protocol - Modbus TCP", "Modbus TCP")
             for i in range(n)])
    add_row("IEEE 1588v2 PTP",
            [sw_val(i, "IEEE 1588v2", "E2E Boundary Clock") for i in range(n)])

    # SFP
    add_sec("SFP Options")
    add_row("Fiber Type",
            [V(hw(i).get("Fiber Type") or "—") for i in range(n)])
    add_row("Fiber Connector",
            [V(hw(i).get("Fiber Connector") or "—") for i in range(n)])

    # 組成 Table
    spec_tbl = Table(rows, colWidths=col_widths, repeatRows=1)

    style_cmds = [
        ("FONTSIZE",       (0, 0), (-1, -1), 8.5),
        ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",     (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 4),
        ("LEFTPADDING",    (0, 0), (-1, -1), 6),
        ("GRID",           (0, 0), (-1, -1), 0.3, GRAY_BD),
        # Header row — 全部產品欄統一深藍底白字
        ("BACKGROUND",     (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR",      (0, 0), (-1, 0), WHITE),
        # Label col
        ("BACKGROUND",     (0, 1), (0, -1), GRAY_LT),
    ]
    for r in sec_row_indices:
        style_cmds += [
            ("BACKGROUND", (0, r), (-1, r),
             colors.HexColor("#D6E4F0")),
            ("SPAN",       (0, r), (-1, r)),
        ]
    for r in diff_row_indices:
        style_cmds.append(
            ("BACKGROUND", (1, r), (-1, r), DIFF_BG)
        )

    spec_tbl.setStyle(TableStyle(style_cmds))
    story.append(spec_tbl)
    story.append(Spacer(1, 4))

    # 圖例
    leg = Table([[
        Paragraph("", PS("lx", 7)),
        Paragraph(
            "  Highlighted cells indicate differences between products",
            PS("ll", 7, color=GRAY_TX),
        ),
    ]], colWidths=[6 * mm, available - 6 * mm])
    leg.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (0, 0), DIFF_BG),
        ("BOX",           (0, 0), (0, 0), 0.4, GRAY_BD),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(leg)
    story.append(Spacer(1, 10))

    # ── Section 3: 參考連結 ───────────────────────────────────────────
    story.append(Paragraph("Product References",
                            PS("h2", 11, True, NAVY, leading=16)))
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=GRAY_BD, spaceAfter=5))

    ref_rows = [[
        Paragraph("<b>Model</b>",    PS("rh",  8, color=WHITE)),
        Paragraph("<b>Part No.</b>", PS("rh2", 8, color=WHITE)),
        Paragraph("<b>Product Page</b>", PS("rh3", 8, color=WHITE)),
    ]]
    for p in products:
        model = p.get("model_name") or p.get("hardware", {}).get("Model Name", "—")
        pn    = p.get("product_pn",  "—")
        url   = (p.get("url")
                 or f"https://www.advantech.com/en/search?q={model}")
        ref_rows.append([
            Paragraph(model, PS("rm", 8, True)),
            Paragraph(pn,    PS("rp", 8, color=GRAY_TX)),
            Paragraph(
                f'<link href="{url}" color="#378ADD">{url}</link>',
                PS("rl", 8),
            ),
        ])

    ref_tbl = Table(ref_rows, colWidths=[38 * mm, 44 * mm, available - 82 * mm])
    ref_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), NAVY),
        ("FONTSIZE",      (0, 0), (-1, -1), 8.5),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, GRAY_LT]),
        ("GRID",          (0, 0), (-1, -1), 0.4, GRAY_BD),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
    ]))
    story.append(ref_tbl)

    # ── Build ─────────────────────────────────────────────────────────
    doc.build(story, canvasmaker=ReportCanvas)
    buffer.seek(0)
    return buffer.read()
